### ISSUE TITLE
build.rs is misused and invoked on any change to sources

### ISSUE THREAD

**Issue by murlakatamenka** [waycrate/wayshot#101]
Current `build.rs` is misused and slows down iteration time, because it only builds docs and doesn't need to run on _any_ change to sources.

In my case, for around ~3 seconds while I work on #95 and #100 

Solutions are well known:

- [`rerun-if-changed`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed) for `docs/*.scd` files
- or to use environment variable to trigger building man pages:

```rs
// build.rs
fn main() {
    if std::env::var("BUILD_DOCS").is_err() {
        std::process::exit(0);
    }

    // build docs if env var is set
}
```

```sh
BUILD_DOCS=1 cargo build --release
```

**Comment by Shinyzenith** [comment]
Hi this has been fixed in our dev branch thanks to @murlakatamenka . Will land in `main` branch soon.
