### ISSUE TITLE
Release tags are gone

### ISSUE THREAD

**Issue by jirutka** [waycrate/wayshot#20]
Why did you remove all the release tags?! These are important (among others) for distributions that package wayshot. I’m maintainer of the wayshot package in Alpine Linux, just wanted to move it from the testing repository to the community repository and noticed that the build is broken due to missing source.

**Comment by Shinyzenith** [comment]
Hi, I am extremely sorry for this. It resulted due to an error on my end while trying to mirror the repository. I am going to move the repo into github instead of sourcehut as packaging is more sane with github. I will fix this right away.

**Comment by Shinyzenith** [comment]
https://github.com/waycrate/wayshot/releases/tag/1.1.5

**Comment by jirutka** [comment]
Thanks for fixing it and also for the decision to use GitHub instead of SourceHut!
