### ISSUE TITLE
Memfd OS restriction is wrong, it should be completely removed.

### ISSUE THREAD

**Issue by HeavyRain266** [waycrate/wayshot#23]
https://github.com/waycrate/wayshot/blob/5f0dbb94cb8b4b375168f8509ce8dd298967a3e8/src/backend.rs#L283

**Comment by Shinyzenith** [comment]
Hi would you mind explaining as to why this should be removed?

**Comment by HeavyRain266** [comment]
> Hi would you mind explaining as to why this should be removed?

**Comment by Shinyzenith** [comment]
> > Hi would you mind explaining as to why this should be removed?
> 
> Memfd is not only linux thing, Linux and FreeBSD support it and those are only platforms with real wayland support

I didn't know it's a thing on freebsd. Will check their man pages just to be sure and promptly remove it.

**Comment by Shinyzenith** [comment]
https://www.freebsd.org/cgi/man.cgi?query=memfd_create&sektion=3&n=1 memfd exists on bsd indeed. Will remove the conditional logic when I get the time.

**Comment by HeavyRain266** [comment]
Thanks, now I'm able to use wayshot on FreeBSD without manual patching
