### ISSUE TITLE
man pages missing in the releases tar.gz file

### ISSUE THREAD

**Issue by akhiljalagam** [waycrate/wayshot#29]
I am using the 1.1.9 release and its missing `docs/*.scd` files. the build is failing.  
why are they not available in the release tarballs ?  

logs:
https://github.com/void-linux/void-packages/runs/8087567118?check_suite_focus=true#step:7:176

void linux package: 
https://github.com/void-linux/void-packages/pull/38546

**Comment by Shinyzenith** [comment]
Hi! First off all, thanks for packaging wayshot. 
I haven't tagged a release with man pages yet. 1.1.9 doesn't have man pages.

I was going through build logs and noticed that you were using shell redirection for scdoc, I have introduced this in build.rs for automatic building if scdoc exists. 

I can tag a release for you later, at work rn.

**Comment by akhiljalagam** [comment]
> Hi! First off all, thanks for packaging wayshot. I haven't tagged a release with man pages yet. 1.1.9 doesn't have man pages.
> 
> I was going through build logs and noticed that you were using shell redirection for scdoc, I have introduced this in build.rs for automatic building if scdoc exists.
> 
> I can tag a release for you later, at work rn.

awesome. thanks.

**Comment by Shinyzenith** [comment]
Apologies for the late reponse, https://github.com/waycrate/wayshot/releases/tag/1.2.0 here's the tag!
