### ISSUE TITLE
vulkan: Setting WLR_RENDERER to vulkan stretches the images

### ISSUE THREAD

**Issue by uncomfyhalomacro** [waycrate/wayshot#34]
Relevant issue - https://github.com/emersion/slurp/issues/121 (Resolved since it's wayshot)

It seems setting `WLR_RENDERER` to `vulkan` is causing wayshot to cause a problem with images.

### Captured with wayshot:

https://user-images.githubusercontent.com/66054069/213844246-8dbc2d73-cf48-42b0-a0e4-4626b1ab74de.png

### Captured with grim:

https://user-images.githubusercontent.com/66054069/213844441-61828ffa-18c9-450b-bbbb-4c3a67797edf.png

**Comment by uncomfyhalomacro** [comment]
Relevant issue: https://github.com/waycrate/wayshot/issues/16

**Comment by Shinyzenith** [comment]
@uncomfyhalomacro What's you compositor version and which version of wlr are you on?

**Comment by uncomfyhalomacro** [comment]
@Shinyzenith it seems it fixed itself for idk what reason
