### ISSUE TITLE
Libwayshot API inclusive of multi monitor setups.

### ISSUE THREAD

**Issue by Shinyzenith** [waycrate/wayshot#46]
Currently all multi output handling is done in wayshot itself. Maybe this could be consolidated into the libwayshot API itself ? 

I don't know if that would be a good API design but I presume most downstream projects would want to support multi-monitor setups and making it trivial in the API itself would reduce fragmentation in the implementations of multi-monitor and overall make it easier for the consumers of the API.

This thread is for further discussion on the topic, feel free to pitch in.

**Comment by c-h-johnson** [comment]
Hi,

I am interested in consolidating the API into libwayshot. Have you made any progress on this?

**Comment by Shinyzenith** [comment]
I have not made any progress in this regard as this is a huge API change. If you'd like to see this happen, feel free to send a PR and we can look over it.
