### ISSUE TITLE
Update clap for atty

### ISSUE THREAD

**Issue by Decodetalkers** [waycrate/wayshot#49]
clap 3.0 will have color, but it is sad that it induced atty... we need to upgrade to 4.0

**Comment by Shinyzenith** [comment]
I'm all for the update to a new version of clap. Why exactly is atty being dropped?

**Comment by Decodetalkers** [comment]
> I'm all for the update to a new version of clap. Why exactly is atty being dropped?

It is unmaintained, and isTerminal is supported by std,so

**Comment by Shinyzenith** [comment]
Okay cool!
