### ISSUE TITLE
blurry image on hidpi screen

### ISSUE THREAD

**Issue by lilydjwg** [waycrate/wayshot#79]
My screen is 3840x2160, but wayshot only produces a 1920x1080 blurry output.

**Comment by Decodetalkers** [comment]
this size of image is by https://github.com/waycrate/wayshot/blob/main/libwayshot/src/dispatch.rs#L168. Reported by wlr-screencopy, but it get blurry, maybe it happened during write to image? if it is because default it is written to png?

**Comment by lilydjwg** [comment]
From `WAYLAND_DEBUG=1` I can see it actually got a 3840x2160 buffer, but since it wanted a 1920x1080 region, it somehow resized it. I didn't find the resizing code, but with a debug build it took seconds to finish (after all the wayland debug logs were printed).

**Comment by lilydjwg** [comment]
[screenshots-rs](https://github.com/nashaofu/screenshots-rs/blob/master/src/linux/wayland.rs) tries to pass unscaled coordinates but it'll get errors because the unscaled coordinates is outside the scaled output space. (It depends on an eariler version of libwayshot however; I updated it.) It seems that with two other screenshot methods (gnome-shell, xdg portal) unscaled coordinates are expected.

**Comment by Decodetalkers** [comment]
If you means 1.3, yes, that time all is resized to the real screen size. but this version when there is only capture one screen, it will not try to resized, https://github.com/waycrate/wayshot/commit/c0906acfaad809b12969d76e0145abbfa340c810 it is fixed in this commit

**Comment by Shinyzenith** [comment]
@Decodetalkers Sure, we can tag a small intermediate release before we land the freeze changes

**Comment by Shinyzenith** [comment]
Hi I have tagged a release with the fix
