### ISSUE TITLE
[bug] "Error: Missing" on no implementation of zwlr_screencopy_v1.

### ISSUE THREAD

**Issue by Shinyzenith** [waycrate/wayshot#9]

**Comment by Shinyzenith** [comment]
wayshot will just print "Error: Missing" when the compositor doesn't implement zwlr_screencopy_v1.

**Comment by HeavyRain266** [comment]
I think it should print `Error: Compositor does not implement zwlr_screencopy_v1 protocol`

**Comment by Shinyzenith** [comment]
> I think it should print `Error: Compositor does not implement zwlr_screencopy_v1 protocol`

I agree.

**Comment by Shinyzenith** [comment]
https://github.com/waycrate/wayshot/commit/6b67b97bc6ad878f9ea91b069943d3953c6548fe
